/**
 * The Stripe payment-link adapter — the external-rail pole.
 *
 * This is the "real rails" leg: the destination is a merchant that did *not* issue our gift card
 * and cannot redeem it, so the split happens on our side. The gift card is drawn on our own store's
 * ledger first; the remainder is settled as a genuine Stripe PaymentIntent in test mode; and if that
 * card leg declines, the gift draw is reversed so the balance lands exactly. One planner reaches
 * this destination with the same four methods it uses for the storefront — the whole point.
 *
 * Honest about what it is: a Stripe Payment Link is a hosted page a human pays, and we do not drive
 * that page headlessly. The link *communicates the amount* (read from Stripe's API by the link's id),
 * and settling it is a real authorization-and-capture on the card rail. Nothing here mocks a success.
 */
import { randomUUID } from "node:crypto";

import Stripe from "stripe";

import type {
  AcceptedInstruments,
  AmountDue,
  InstrumentPlan,
  Mandate,
  PaymentDestination,
  PaymentResult,
  PaymentStatus,
} from "../destination.js";
import type { Minor } from "../money.js";

/** Pull a `plink_…` id out of whatever reference the agent was handed. */
function paymentLinkId(reference: string): string {
  const match = reference.match(/plink_[A-Za-z0-9]+/);
  if (match) return match[0];
  if (reference.startsWith("plink_")) return reference;
  throw new Error(
    `payment-link reference must be a Stripe payment link id (plink_…); got "${reference}"`,
  );
}

/**
 * Draw the gift card on our ledger under a caller-supplied run id.
 *
 * The run id is generated by the caller *before* this is called, and sent in, so that a draw whose
 * HTTP response is lost (a dropped connection, a 500 after the ledger write) is still reversible by
 * that id. Returns what the ledger actually drew — which may be less than asked when the card holds
 * less than the stale hint suggested.
 */
async function redeemGift(
  storeBase: string,
  gift: { code: string; pin: string },
  amountMinor: Minor,
  runId: string,
): Promise<Minor> {
  const res = await fetch(`${storeBase}/funding/redeem`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ code: gift.code, pin: gift.pin, amount_minor: amountMinor, run_id: runId }),
  });
  const body = (await res.json()) as { drawn_minor?: number; detail?: string };
  if (!res.ok) throw new Error(body.detail ?? `gift-card redeem failed (${res.status})`);
  return body.drawn_minor ?? 0;
}

/** Hand a drawn run back. Returns whether the reversal actually succeeded — never assumed. */
async function reverseGift(storeBase: string, runId: string): Promise<boolean> {
  try {
    const res = await fetch(`${storeBase}/funding/reverse`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ run_id: runId }),
    });
    return res.ok;
  } catch {
    return false;
  }
}

export function stripePaymentLink(opts: {
  secretKey: string;
  storeBaseUrl: string;
}): PaymentDestination {
  // Test mode only. A live key in here is refused outright — the same mechanical guard the store
  // uses, because an agent settling real money against a link is not what M2 is.
  if (!opts.secretKey.startsWith("sk_test_")) {
    throw new Error(
      "payment-link adapter is test-mode only; its key must be an sk_test_… key",
    );
  }
  const stripe = new Stripe(opts.secretKey, {
    appInfo: { name: "pay-agent-agent", url: "https://github.com/ashis-majumder/pay-agent" },
  });
  const storeBase = opts.storeBaseUrl.replace(/\/$/, "");

  return {
    id: "stripe-payment-link",

    /** Read the amount owed from the link itself, via Stripe — never scraped, never hardcoded. */
    async discover(reference: string): Promise<AmountDue> {
      const id = paymentLinkId(reference);
      const items = await stripe.paymentLinks.listLineItems(id, { limit: 100 });
      let amountMinor = 0;
      let currency = "";
      for (const item of items.data) {
        // amount_total is the line's quantity × unit price in minor units, tax included.
        amountMinor += item.amount_total;
        currency = item.currency ?? currency;
      }
      if (amountMinor <= 0 || !currency) {
        throw new Error(`payment link ${id} exposed no payable amount`);
      }
      return {
        destinationId: this.id,
        reference,
        amountMinor,
        currency: currency.toUpperCase(),
        description: `hosted payment link ${id}`,
        handle: id,
      };
    },

    /** An external merchant: it takes a card, and it cannot redeem our closed-loop gift card. */
    async capabilities(): Promise<AcceptedInstruments> {
      return { currency: "CAD", redeemsGiftCard: false, acceptsCard: true };
    },

    /**
     * Draw the gift card on our ledger, settle the remainder on the card rail, and — if that leg
     * fails — reverse the draw. The gift draw and its reversal are the failure-safety spine: once
     * money is drawn, anything that throws before the card settles hands it straight back.
     */
    async pay(plan: InstrumentPlan, _mandate: Mandate, due: AmountDue): Promise<PaymentResult> {
      const gift = plan.giftDrawMinor > 0 ? plan.giftCard : null;
      // The reversible run id is minted before any draw, so a redeem whose response is lost is
      // still reversible by this id. `attemptedDraw` flips true the instant before the call, so the
      // catch reverses even when redeemGift itself throws after the ledger already moved.
      const giftRunId = gift ? `agent_${randomUUID()}` : null;
      let attemptedDraw = false;
      let giftDrawn: Minor = 0;

      /** Unwind a draw and fold the honest reversal outcome into a failure result. */
      const failReversed = async (detail: string): Promise<PaymentResult> => {
        let reversed = false;
        if (attemptedDraw && giftRunId) reversed = await reverseGift(storeBase, giftRunId);
        return {
          ok: false,
          handle: "",
          detail:
            attemptedDraw && !reversed
              ? `${detail} — WARNING: gift draw ${giftRunId} could NOT be reversed; run left open`
              : detail,
          giftDrawnMinor: null,
          cardChargedMinor: null,
          reversed,
        };
      };

      try {
        if (gift && giftRunId) {
          attemptedDraw = true;
          giftDrawn = await redeemGift(storeBase, gift, plan.giftDrawMinor, giftRunId);
        }

        // Reconcile the card leg against what the gift card ACTUALLY drew, not the plan's estimate.
        // A stale-high hint draws less than planned, so the card must cover the true remainder — a
        // number still bounded by the amount due, which is what the mandate authorized. Charging
        // `plan.cardMinor` here would silently underpay the bill and report it settled.
        const cardAmount = due.amountMinor - giftDrawn;

        if (cardAmount <= 0) {
          // The gift card covered the whole bill; there is no external leg to run.
          return {
            ok: true,
            handle: giftRunId ?? "gift-only",
            detail: `gift card covered the whole ${due.description}`,
            giftDrawnMinor: giftDrawn > 0 ? giftDrawn : null,
            cardChargedMinor: 0,
            reversed: false,
          };
        }

        if (!plan.card) {
          return failReversed(`${cardAmount} remained after the gift card and no card was granted`);
        }

        const intent = await stripe.paymentIntents.create(
          {
            amount: cardAmount,
            currency: due.currency.toLowerCase(),
            payment_method: plan.card.token,
            confirm: true,
            // The buyer is not at a browser — an agent is settling this. `off_session` is Stripe's
            // own name for that, and it makes a decline here a genuine issuer decline. (off_session
            // already precludes redirect-based methods, so no automatic_payment_methods is needed.)
            off_session: true,
            metadata: { destination: this.id, payment_link: due.handle, run_id: giftRunId ?? "none" },
          },
          // The idempotency key carries this run's own nonce (the gift run id, or a fresh one when
          // there was no gift leg), so retries within a run coalesce but two distinct purchases of
          // the same amount never collide onto one intent.
          { idempotencyKey: `${giftRunId ?? randomUUID()}:${cardAmount}` },
        );

        if (intent.status !== "succeeded") {
          return failReversed(`card authorization did not settle (status: ${intent.status})`);
        }

        return {
          ok: true,
          handle: intent.id,
          detail: `settled ${cardAmount} on ${intent.id}`,
          giftDrawnMinor: giftDrawn > 0 ? giftDrawn : null,
          cardChargedMinor: cardAmount,
          reversed: false,
        };
      } catch (err) {
        // A connection/API error is indeterminate: Stripe may have captured and only the response
        // was lost. Reversing the gift now would leave a charged card beside a refunded gift — an
        // underpayment. So do NOT reverse on an indeterminate transport error; leave the draw in
        // place and surface it with the run id, because a stuck-but-recoverable draw is safer than
        // silently collecting less than the bill.
        if (
          err instanceof Stripe.errors.StripeConnectionError ||
          err instanceof Stripe.errors.StripeAPIError
        ) {
          return {
            ok: false,
            handle: "",
            detail:
              `indeterminate: the card charge may or may not have settled (${err.message})` +
              (attemptedDraw
                ? `; gift draw ${giftRunId} left in place pending reconciliation — do not retry blindly`
                : ""),
            giftDrawnMinor: attemptedDraw ? giftDrawn : null,
            cardChargedMinor: null,
            reversed: false,
          };
        }
        // A definite decline (a card error) or other failure: no capture happened, so unwind.
        const detail =
          err instanceof Stripe.errors.StripeError
            ? `${err.code ?? err.type}: ${err.message}`
            : err instanceof Error
              ? err.message
              : String(err);
        return failReversed(detail);
      }
    },

    /** Ask Stripe what became of the charge, rather than trusting `pay`'s return. */
    async confirm(handle: string): Promise<PaymentStatus> {
      if (!handle.startsWith("pi_")) {
        // No card leg ran (gift covered it all), so there is nothing on Stripe to confirm.
        return { settled: true, handle, detail: "no card leg — gift card settled it" };
      }
      const intent = await stripe.paymentIntents.retrieve(handle);
      return {
        settled: intent.status === "succeeded",
        handle,
        detail: `payment intent ${intent.status}`,
      };
    },
  };
}
